name: Create GitHub release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${GITHUB_REF#refs/tags/}
